Hw7
maxosad/homework pull request #15
Opened 2023-11-21 21:49 UTC by maxosad

In task4 run main

2023-12-14 19:35 UTC, SHvatov requested changes
@maxosad оставил пару комментариев, посмотри их, пожалуйста.

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/Task1.java
> +        } catch (InterruptedException e) {
Советую посмотреть в сторону использования lombok. К примеру, в данном случае можно было бы использовать @SneakyThrows.

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/Task2.java
> +            .reduce((firstOperand, secondOperand) -> firstOperand * secondOperand).orElse(0);
Можно классические lhs, rhs или просто left и right для краткости)

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/task3/PersonDatabase.java
> +    @Nullable Person findByName(String name);
Аннотации стоит держать над методами ради единообразность, особенно когда их становится много.

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/task3/PersonDatabaseImpl.java
> +
Лишняя пустая строка

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/task3/PersonDatabaseImpl.java
> +    private Map<String, Person> nameCollection;
То, что это коллекция, понятно и из типа) Можно дать более говорящее и более стандартное наименование для таких мап - `сущностьByКлюч`. К примеру - `personsByName`. И еще момент - у нескольких человек может быть одно и то же имя.

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/task3/PersonDatabaseImpl.java
> +    private Map<String, Person> nameCollection;
Еще бы для таких задач я бы советовал использовать обратные индексы - https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81#:~:text=inverted%20index)%20%E2%80%94%20%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%2C,%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B5%D1%82%D1%81%D1%8F%20%D0%B4%D0%BB%D1%8F%20%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0%20%D0%BF%D0%BE%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0%D0%BC. То есть хранить по имени человека список ИД людей с таким именем. На то есть несколько причин - основная это то, что ИД чаще всего прост с точки зрения сравнения, что ускоряет поиск.

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/task3/PersonDatabaseImpl.java
> +    public synchronized @Nullable Person findByName(String name) {
аннотация уехала

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/task3/ReadWriteLockDatabase.java
> +        lock.writeLock().lock();
1. все, что после lock() стоит обернуть в try/catch, и unlock сделать в finally (вообще советую все работы с ресурсами делать через try/finally)
2. также советую в будущем использовать tryLock, чтобы вызывающий поток не висел 100500 лет в ожидании лока

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/task4/Error.java
> +    double experiments10000,
нейминг так себе) лучше бы мапкой хранить

2023-12-14 19:35 UTC, SHvatov commented on src/main/java/edu/hw7/task4/LinearMonteCarlo.java
> +
ой, сколько пустых и ненужных строк)

2023-12-14 19:35 UTC, SHvatov commented on src/test/java/edu/hw7/Task1Test.java
> +    @ParameterizedTest
а вот тут уже не хватает пустой строки

2023-12-23 16:13 UTC, maxosad commented on src/main/java/edu/hw7/Task1.java
> +        } catch (InterruptedException e) {
поставил @SneakyThrows, убрал try catch

2023-12-23 16:15 UTC, maxosad commented on src/main/java/edu/hw7/Task2.java
> +            .reduce((firstOperand, secondOperand) -> firstOperand * secondOperand).orElse(0);
поставил left и right

2023-12-23 16:15 UTC, maxosad commented on src/main/java/edu/hw7/task3/PersonDatabase.java
> +    @Nullable Person findByName(String name);
поправил форматирование

2023-12-23 16:16 UTC, maxosad commented on src/main/java/edu/hw7/task3/PersonDatabaseImpl.java
> +
убрал

2023-12-23 16:20 UTC, maxosad commented on src/main/java/edu/hw7/task3/PersonDatabaseImpl.java
> +    public synchronized @Nullable Person findByName(String name) {
поправил

2023-12-23 16:22 UTC, maxosad commented on src/main/java/edu/hw7/task4/LinearMonteCarlo.java
> +
поправил

2023-12-23 16:22 UTC, maxosad commented on src/test/java/edu/hw7/Task1Test.java
> +    @ParameterizedTest
поправил

2023-12-23 16:57 UTC, merged