Hw8
maxosad/homework pull request #16
Opened 2023-12-03 16:16 UTC by maxosad

2023-12-14 20:52 UTC, SHvatov requested changes
@maxosad оставил комментарии, посмотри их, пожалуйста.

2023-12-14 20:52 UTC, SHvatov commented on pom.xml
> +            <artifactId>jaxb-api</artifactId>
а где у нас XML-ки используются?)

2023-12-14 20:52 UTC, SHvatov commented on pom.xml
> +            <version>2.3.1</version>
и версии зависимостей я бы советовал хранить в пропертях - так проще за ними следить

2023-12-14 20:52 UTC, SHvatov commented on src/main/java/edu/hw8/task1/Client.java
> +        return ans;
1. можно на 21 строке просто сделать return и не париться с такой переменной
2. try/catch выглядит как кандидат для @SneakyThrows из ломбока)

2023-12-14 20:52 UTC, SHvatov commented on src/main/java/edu/hw8/task1/MonoThreadClientHandler.java
> +    private static final Map<String, String> SAYING_DICT = new HashMap<>();
1. `Map.of`, и можно не париться со статик блоком
2. лучше, когда сначала идут статики, а потом поля класса - стандартное расположение полей и так проще в них ориентироваться

2023-12-14 20:52 UTC, SHvatov commented on src/main/java/edu/hw8/task1/MonoThreadClientHandler.java
> +
лишняя пустая строка

2023-12-14 20:52 UTC, SHvatov commented on src/main/java/edu/hw8/task1/MonoThreadClientHandler.java
> +        } catch (EOFException ignore) {
исключения лучше не игнорить

2023-12-14 20:52 UTC, SHvatov commented on src/main/java/edu/hw8/task1/Server.java
> +                if (clientNumber.incrementAndGet() <= maxConnections) {
а если их больше? просто игнориуем клиента?

2023-12-14 20:52 UTC, SHvatov commented on src/main/java/edu/hw8/task1/Server.java
> +                    isEnded.get();
не лучшее использование фьючеров

2023-12-14 20:52 UTC, SHvatov commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +        Arrays.stream(threads).forEach(Thread::interrupt);
Метод не гарантирует, что все потоки реально остановились - какие-то будут заинтерапчены, но все еще выполнять поставленную задачу. А мы к этому моменту времени давно вышли из метода close. Я бы заджойнил все потоки к тому, который вызвал закрытие. Еще хорошо бы обрабатывать кейс параллельного закрытия пула.

2023-12-14 20:52 UTC, SHvatov commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +            taskQueue.put(runnable);
Можем класть в очередь задачи даже после закрытия пула

2023-12-14 22:13 UTC, maxosad commented on src/main/java/edu/hw8/task1/Server.java
> +                if (clientNumber.incrementAndGet() <= maxConnections) {
Я думал, что если их больше, ты мы пока не акцептимся, потом, когда место будет заакцептимся, разве так не работает?

2023-12-14 22:14 UTC, maxosad commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +            taskQueue.put(runnable);
добавил переменную isClosed

2023-12-14 22:15 UTC, maxosad commented on src/main/java/edu/hw8/task1/Client.java
> +        return ans;
сделал return на 21 строке

2023-12-14 22:15 UTC, maxosad commented on src/main/java/edu/hw8/task1/MonoThreadClientHandler.java
> +    private static final Map<String, String> SAYING_DICT = new HashMap<>();
Сделал Map.of и упорядочил переменные

2023-12-14 22:15 UTC, maxosad commented on src/main/java/edu/hw8/task1/MonoThreadClientHandler.java
> +
удалили ее

2023-12-14 22:29 UTC, maxosad commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +        Arrays.stream(threads).forEach(Thread::interrupt);
поджойнил потоки, сделал метод close синхронезированным

2023-12-14 22:31 UTC, maxosad commented on pom.xml
> +            <artifactId>jaxb-api</artifactId>
пома не касался

2023-12-14 22:38 UTC, maxosad commented on pom.xml
> +            <artifactId>jaxb-api</artifactId>
Когда я еще 1 ые домашки сдавал checkstyle не работал. C помощью жтого пытался поправить с ним проблему. 
Я так понимаю используется в файле checkstyle.xml

2023-12-14 22:38 UTC, maxosad commented on pom.xml
> +            <version>2.3.1</version>
внес в properties

2023-12-14 22:47 UTC, maxosad commented on src/main/java/edu/hw8/task1/MonoThreadClientHandler.java
> +        } catch (EOFException ignore) {
может быть вы подскажите как читать до конца,
потому что у меня String key = in.readUTF(); 
читает в какой - то момент падает с EOFException, хотя как я понимааю он должен хотябы на пред чтении вернуть null, но не возвращает

2023-12-14 22:56 UTC, maxosad commented on src/main/java/edu/hw8/task1/Server.java
> +                    isEnded.get();
в моем понимании мы должны освободить место, когда поток закончит выполняться, с помощью них я дожидаюсь, что поток закончил

2023-12-15 12:32 UTC, maxosad commented on src/main/java/edu/hw8/task1/Client.java
> +        return ans;
добавил  @SneakyThrows

2023-12-19 16:01 UTC, SHvatov commented on pom.xml
> +            <artifactId>jaxb-api</artifactId>
да, все верно

странное решение, но ладно, не критично

2023-12-19 16:02 UTC, SHvatov commented on src/main/java/edu/hw8/task1/Server.java
> +                if (clientNumber.incrementAndGet() <= maxConnections) {
Но сейчас же получается, что ему просто вернется пустой ответ. С таким сервисом будет очень сложно работать)

2023-12-19 16:03 UTC, SHvatov commented on src/main/java/edu/hw8/task1/Server.java
> +                    isEnded.get();
сам комментарий на будущее, get стоит вызывать в самый последний момент, а то никакого смысла от фьючеров не будет

2023-12-19 16:04 UTC, SHvatov approved these changes
@maxosad 🆗, можно мержить

2023-12-23 17:02 UTC, merged