Hw9
maxosad/homework pull request #17
Opened 2023-12-06 15:17 UTC by maxosad

2023-12-15 09:38 UTC, SHvatov requested changes
@maxosad оставил комментарии по первой задаче, 2 и 3 👍

2023-12-15 09:38 UTC, SHvatov commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +    public void push(String name, double[] data) {
Думаю, по заданию не все так просто)

Набор метрик ограничен, и по ним приходят какие-то данные - то есть помимо обычной агрегации, тебе итоговые статы нужно хранить, чтобы потом их обновлять. К примеру:

```java
push("latency", {0, 0, 0.01, 0, 0.2});
... // какое-то время прошло
push("latency", {0, 0});
var res = stats(); // хочу тут получить агрегированную стату по latency за все время
```

2023-12-15 09:38 UTC, SHvatov commented on src/main/java/edu/hw9/task2/FindDirectories.java
> +
пустая строка никому не нужна 😞

2023-12-15 09:38 UTC, SHvatov commented on src/main/java/edu/hw9/task2/files/bigPhp.php
> +qwertyuiwertyuasdfghjsdfghj
о, узнаю код на пхп)

а вообще такие тестовые файлы и директории стоит держать в тестах) а еще лучше создавать их там через [TempDir](https://www.baeldung.com/junit-5-temporary-directory)

2023-12-17 13:43 UTC, maxosad commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +    public void push(String name, double[] data) {
добавил такой функционал

2023-12-17 13:43 UTC, maxosad commented on src/main/java/edu/hw9/task2/FindDirectories.java
> +
убрал ее

2023-12-17 13:43 UTC, maxosad commented on src/main/java/edu/hw9/task2/files/bigPhp.php
> +qwertyuiwertyuasdfghjsdfghj
переместил папку в тесты

2023-12-19 15:57 UTC, SHvatov approved these changes
@maxosad 👍, можно мержить)

2023-12-23 17:07 UTC, merged