some results
maxosad/homework pull request #18
Opened 2023-12-10 02:34 UTC by maxosad

2023-12-17 11:31 UTC, SHvatov commented on src/main/java/edu/project4/files/image0.png
Такие файлы лучше хранить в директории main/resources, либо вообще утащить в директорию в корне проекта, если это файлы для ридми.

2023-12-17 11:37 UTC, SHvatov requested changes
@maxosad оставил пару минорных комментариев. Особенно не нравится использование публичного листа, который может быть изменен кем угодно откуда угодно - где же любимая всеми инкапсуляция данных?) Поправь это, и мы в расчете.

2023-12-17 11:37 UTC, SHvatov commented on src/main/java/edu/project4/model/Affine.java
> +public record Affine(double a,
`Affine` - не самое очевидное название, ИМХО лучше `AffineCoefficients` + rgb вынести в отдельный рекорд.

2023-12-17 11:37 UTC, SHvatov commented on src/main/java/edu/project4/model/ImageFormat.java
> +
ненужная пустая строка

2023-12-17 11:37 UTC, SHvatov commented on src/main/java/edu/project4/processing/ImageProcessor.java
> +interface ImageProcessor {
зачем этот перенос?

2023-12-17 11:37 UTC, SHvatov commented on src/main/java/edu/project4/render/AffineCoeff.java
> +                    random.nextInt(256), random.nextInt(256), random.nextInt(256)
256 очень даже хорошо выносится в константу типа MAX_RGB_VALUE

2023-12-17 11:37 UTC, SHvatov commented on src/main/java/edu/project4/render/AffineCoeff.java
> +    public static final List<Affine> COEFF = new ArrayList<>();
такое себе решение, потому что любой может на листе вызвать `add` или `clear`, а потом разбирайся - кто и где испортил лист с коэффициентами)

2023-12-17 11:37 UTC, SHvatov commented on src/main/java/edu/project4/render/LinearRenderer.java
> +//    public static final double X_MIN = -1.777;
закомментированный код 🗑️

2023-12-17 11:37 UTC, SHvatov commented on src/main/java/edu/project4/render/ParallelRenderer.java
> +        Runnable task = () -> {
Почему бы не вынести в метод?

2023-12-17 11:37 UTC, SHvatov commented on src/test/java/edu/project4/model/FractalImageTest.java
> +        width = 1920;
а зачем?) почему бы не константами?

2023-12-23 15:58 UTC, maxosad commented on src/main/java/edu/project4/model/ImageFormat.java
> +
убрал

2023-12-23 16:04 UTC, maxosad commented on src/main/java/edu/project4/model/Affine.java
> +public record Affine(double a,
Affine переименовал, 
rgb вынес

2023-12-23 16:05 UTC, maxosad commented on src/main/java/edu/project4/processing/ImageProcessor.java
> +interface ImageProcessor {
убрал

2023-12-23 16:05 UTC, maxosad commented on src/main/java/edu/project4/render/AffineCoeff.java
> +                    random.nextInt(256), random.nextInt(256), random.nextInt(256)
вынес в константу MAX_RGB_VALUE

2023-12-23 16:06 UTC, maxosad commented on src/main/java/edu/project4/render/AffineCoeff.java
> +    public static final List<Affine> COEFF = new ArrayList<>();
убрал, теперь в статик блоке присваиваю иммутабле лист

2023-12-23 16:06 UTC, maxosad commented on src/main/java/edu/project4/render/LinearRenderer.java
> +//    public static final double X_MIN = -1.777;
убрал

2023-12-23 16:07 UTC, maxosad commented on src/test/java/edu/project4/model/FractalImageTest.java
> +        width = 1920;
вынес в константы

2023-12-23 17:10 UTC, merged