Project1
maxosad/homework pull request #2
Opened 2023-10-12 23:13 UTC by maxosad

All project1 with tests

2023-10-23 13:24 UTC, nexen505 requested changes

2023-10-23 13:24 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +        status = GameStatus.IN_PROGRESS;
Проблема: судя по всему, из-за этого при обычном запуске `Main` программа вывела сообщение и завершилась с кодом 0:
`17:09:45.681 INFO  [main           ] u.project1.Conf -- current session should be in progress`

Предложение: исправить флоу игры, чтобы она запускалась корректно.

2023-10-23 13:24 UTC, nexen505 commented on src/main/java/edu/project1/FixedDictionary.java
> +    public FixedDictionary(String[] dict) {
Косметика: выглядит так, что тут надо принимать одну строку, раз вернуться может лишь одна. В родительский конструктор можно массив из одного элемента передать.

2023-10-23 13:24 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +    public void newSession() {
Косметика: метод не используется - можно удалить.

2023-10-23 13:24 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +    private final Integer wordToGuessLength;
Предложение: вместо этого поля можно пользоваться `currentWord.size()`

2023-10-23 13:24 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +    public static final String GIVE_UP_PHRASE = "give up";
Косметика: с точки зрения UX, хорошо пользователю подсказать, что эта фраза завершит игру.

2023-10-23 13:51 UTC, maxosad commented on src/main/java/edu/project1/FixedDictionary.java
> +    public FixedDictionary(String[] dict) {
Добавил конструктор из одной строки. 
Оставил конструктор с String[], потому, что он есть в AbstractDictionary.

2023-10-23 13:52 UTC, maxosad commented on src/main/java/edu/project1/Game.java
> +    public void newSession() {
использовал его в конструкторе. Он написан для дальнейшего использования. С помощью него можно получить другое слово в рамках одной игры.

2023-10-23 13:54 UTC, maxosad commented on src/main/java/edu/project1/Session.java
> +        status = GameStatus.IN_PROGRESS;
Да, проблема была. 
Было написано 
` if (status.equals(GameStatus.IN_PROGRESS)) {
            return AnswerStatus.SESSION_ENDED;
        }`
Из - за этого он вылетал, заменил на 
` if (!status.equals(GameStatus.IN_PROGRESS)) {
            return AnswerStatus.SESSION_ENDED;
        }`

2023-10-23 13:58 UTC, maxosad commented on src/main/java/edu/project1/Session.java
> +    public static final String GIVE_UP_PHRASE = "give up";
Тепер при начеле сессии это подсвечивается

2023-10-23 13:58 UTC, maxosad commented on src/main/java/edu/project1/Session.java
> +    private final Integer wordToGuessLength;
пофиксил

2023-10-27 10:58 UTC, nexen505 requested changes

2023-10-27 10:58 UTC, nexen505 commented on src/main/java/edu/project1/FixedDictionary.java
> +    public FixedDictionary(String[] dict) {
Семантически в конструкторе в массивом нет смысла, так как в итоге все равно берется одно слово и родительский класс тут ни при чем.

2023-10-27 10:58 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +                        default -> { }
Проблема: в случае некорректного ввода непонятно, что не так с ним.

Предложение: добавить подсказку пользователю, что ожидается одна буква.

2023-10-27 10:58 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +                    LOGGER.info("> Guess a letter:");
Проблема: при первом вводе пользователь не знает, какого размера слово надо угадывать.

Предложение: добавить вывод зашифрованного слова при входе в игру.

2023-10-27 10:58 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +    private Integer currentAttempt;
Проблема: тут и в других местах с числами нет смысла пользоваться `boxed`-типами.

Предложение: использовать примитивные типы.

2023-10-27 10:58 UTC, nexen505 commented on src/main/java/edu/project1/RandomDictionary.java
> +        return dict[random.nextInt(dict.length + 1)];
Проблема: может выпасть `ArrayIndexOutOfBoundsException`.

Предложение:

```java suggestion
        return dict[random.nextInt(dict.length)];
```

2023-10-27 10:58 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +            boolean wasGuessed = false;
Проблема: повторный ввод ранее неугаданной буквы приводит к трате попытки и поражению.

Предложение: предусмотреть, чтобы траты попытки не происходило, и вывести пользователю просьбу указать другую букву.

2023-10-27 10:58 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +        StringBuilder sb = new StringBuilder();
Косметика: для оптимизации работы с памятью в случае известного размера `StringBuilder` стоит передать его через конструктор.

2023-10-27 10:58 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +                    session.printCurrentWord();
Проблема: при проигрыше пользователь не узнает, что за слово было.

Предложение: вывести в конце проигранной игры пользователю загаданное слово.

2023-11-01 05:38 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +                    session.printCurrentWord();
Проблема осталась.

2023-11-01 05:40 UTC, nexen505 requested changes

2023-11-01 05:40 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +    private final Map<Character, Boolean> usedWrongLetters;
Мысль: при таком использовании это то же самое, что `Set<Character>`

2023-11-03 13:25 UTC, nexen505 approved these changes

2023-11-03 21:53 UTC, merged