Hw2
maxosad/homework pull request #7
Opened 2023-10-15 12:28 UTC by maxosad

hw2

2023-10-19 06:06 UTC, nexen505 requested changes

2023-10-19 06:06 UTC, nexen505 commented on src/main/java/edu/hw2/task2/Rectangle.java
> +        return width * height;
Проблема: тип произведения не соответствует объявленному типу метода.

Предложение: исправить приведением типов.

2023-10-19 06:06 UTC, nexen505 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        Connection connection = manager.getConnection();
Проблема: логика `retry` не учитывает возможную ошибку при открытии соединения. Кроме того, при очередном `retry` соединение будет закрыто, что может не позволить выполнять команды на нем. Причем в текущих тестах это не отловить, так как при попытке `execute` на закрытом соединении тоже выбрасывается `ConnectionException`.

Предложение: открывать соединение на каждую попытку.

2023-10-19 06:06 UTC, nexen505 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +                break;
Предложение: делать здесь явный `return` для упрощения логики.

2023-10-19 06:06 UTC, nexen505 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        boolean executed = false;
Мысль: от использования этого флага можно уйти, если бросать исключение на последней попытке в блоке `catch`.

2023-10-19 06:06 UTC, nexen505 commented on src/test/java/edu/hw2/task3/ConnectionTest.java
> +            fail();
Проблема: такое использование не выразительно и затрудняет понимание, почему тест упал.

Предложение: тут и в других местах передать в метод сообщение с пояснением, почему тест упал, и причиной-исключением, где это возможно, как в данном случае.

2023-10-19 12:45 UTC, maxosad commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        Connection connection = manager.getConnection();
В условии не сказанно, про ошибки при открытии соединения. 
Единственное, что про это написано - это "проблемное соединение иногда бросает ConnectionException"
Я так понял, что это значит при вызове execute он может выдать exception.

Про то, что manager.getConnection(); может выдать исключение я в условии не нахожу.

добави конструктор ConnectionException с месседжом ошибки 
теперь при execute closed будет соответствующий месседж ошибки и 
при close closed тоже. Добавил к этому тесты

Сделал, что в каждом try новое соединение

2023-10-20 06:13 UTC, nexen505 approved these changes
Nice.

2023-10-20 08:47 UTC, merged